version: "3"
tasks:
  compiler:
    cmds:
      - go run ./compiler {{.CLI_ARGS}}
  test:
    cmds:
      - go test work
  install:
    cmds:
      - go install ./compiler
  vscode:
    dir: vscode
    cmds:
      - npm run extension
