version: "3"
tasks:
  setup:
    cmds:
      - cd compiler && npm install
      - cd vscode && npm install
  compile:
    cmd: (cd compiler && npm run build) && node compiler compile {{.CLI_ARGS}}
    env:
      NODE_OPTIONS: "--enable-source-maps"
  test:
    dir: compiler
    cmd: npm test
  install:
    cmd: (cd compiler && npm run exe)
