version: "3"
tasks:
    setup:
        cmds:
            - npm install
    build:
        cmds:
            - (cd compiler && npm run build)
    compiler:
        deps:
            - build
        cmds:
            - node compiler {{.CLI_ARGS}}
        env:
            NODE_OPTIONS: "--enable-source-maps"
    profile:
        deps:
            - build
        cmds:
            - node --cpu-prof compiler {{.CLI_ARGS}}
        env:
            NODE_OPTIONS: "--enable-source-maps"
    test:
        deps:
            - build
        cmds:
            - (cd compiler && npm run test -- {{.CLI_ARGS}})
            - (cd tests && npx vitest run {{.CLI_ARGS}})
    install:
        deps:
            - build
        cmds:
            - (cd compiler && npm run exe)
    vscode:
        dir: vscode
        cmds:
            - npm run extension
